// Tetrapoda-Ergänzung für Ryos Lernarchiv v0.2.6
// Wird nach data.js und vor script.js geladen.
(function(){
  const DATA = window.LEARNING_ARCHIVE_DATA;
  if (!DATA || !Array.isArray(DATA.animals)) return;
  const entries = [
  {
    "id": "animal-feuersalamander",
    "group": "animals",
    "number": 272,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Amphibia",
    "classGerman": "Amphibien",
    "order": "Urodela",
    "orderGerman": "Schwanzlurche",
    "family": "Salamandridae",
    "familyGerman": "Echte Salamander und Molche",
    "scientificName": "Salamandra salamandra",
    "displayName": "Salamandra salamandra",
    "genus": "Salamandra",
    "germanName": "Feuersalamander",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/feuersalamander.jpg",
    "traits": [
      "schwarz-gelbe Warnfärbung",
      "Schwanzlurch",
      "Ovoviviparie: kiementragende Larven werden geboren"
    ],
    "confusableWith": [
      "Alpensalamander"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-alpensalamander",
    "group": "animals",
    "number": 273,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Amphibia",
    "classGerman": "Amphibien",
    "order": "Urodela",
    "orderGerman": "Schwanzlurche",
    "family": "Salamandridae",
    "familyGerman": "Echte Salamander und Molche",
    "scientificName": "Salamandra atra",
    "displayName": "Salamandra atra",
    "genus": "Salamandra",
    "germanName": "Alpensalamander",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/alpensalamander.jpg",
    "traits": [
      "meist vollständig schwarz",
      "Schwanzlurch",
      "Viviparie: lungenatmende Jungtiere werden geboren"
    ],
    "confusableWith": [
      "Feuersalamander"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-teichmolch",
    "group": "animals",
    "number": 274,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Amphibia",
    "classGerman": "Amphibien",
    "order": "Urodela",
    "orderGerman": "Schwanzlurche",
    "family": "Salamandridae",
    "familyGerman": "Echte Salamander und Molche",
    "scientificName": "Lissotriton vulgaris",
    "displayName": "Lissotriton vulgaris",
    "genus": "Lissotriton",
    "germanName": "Teichmolch",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/teichmolch.jpg",
    "traits": [
      "kleiner Molch",
      "Oviparie",
      "gelegentlich Neotenie"
    ],
    "confusableWith": [
      "Bergmolch"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-bergmolch",
    "group": "animals",
    "number": 275,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Amphibia",
    "classGerman": "Amphibien",
    "order": "Urodela",
    "orderGerman": "Schwanzlurche",
    "family": "Salamandridae",
    "familyGerman": "Echte Salamander und Molche",
    "scientificName": "Ichthyosaura alpestris",
    "displayName": "Ichthyosaura alpestris",
    "genus": "Ichthyosaura",
    "germanName": "Bergmolch",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/bergmolch.jpg",
    "traits": [
      "orange Bauchseite möglich",
      "bläuliche Färbung beim Männchen möglich",
      "Oviparie; Neotenie relativ häufig"
    ],
    "confusableWith": [
      "Teichmolch"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-gelbbauchunke",
    "group": "animals",
    "number": 276,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Amphibia",
    "classGerman": "Amphibien",
    "order": "Anura",
    "orderGerman": "Froschlurche",
    "family": "Bombinatoridae",
    "familyGerman": "Unken",
    "scientificName": "Bombina variegata",
    "displayName": "Bombina variegata",
    "genus": "Bombina",
    "germanName": "Gelbbauchunke",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/gelbbauchunke.jpg",
    "traits": [
      "gelb-schwarze Unterseite",
      "Schreckfärbung",
      "richtet sich bei Gefahr auf"
    ],
    "confusableWith": [
      "Erdkröte",
      "Wechselkröte",
      "Grasfrosch"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-grasfrosch",
    "group": "animals",
    "number": 277,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Amphibia",
    "classGerman": "Amphibien",
    "order": "Anura",
    "orderGerman": "Froschlurche",
    "family": "Ranidae",
    "familyGerman": "Echte Frösche",
    "scientificName": "Rana temporaria",
    "displayName": "Rana temporaria",
    "genus": "Rana",
    "germanName": "Grasfrosch",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/grasfrosch.jpg",
    "traits": [
      "braun um Augen",
      "Echte Frösche machen Laichballen",
      "Froschlurch ohne Schwanz"
    ],
    "confusableWith": [
      "Erdkröte",
      "Laubfrosch"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-laubfrosch",
    "group": "animals",
    "number": 278,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Amphibia",
    "classGerman": "Amphibien",
    "order": "Anura",
    "orderGerman": "Froschlurche",
    "family": "Hylidae",
    "familyGerman": "Laub-/Baumfrösche",
    "scientificName": "Hyla arborea",
    "displayName": "Hyla arborea",
    "genus": "Hyla",
    "germanName": "Laubfrosch",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/laubfrosch.jpg",
    "traits": [
      "grün",
      "dicke Finger / Haftscheiben",
      "keine Schwimmhäute laut Screenshotnotiz"
    ],
    "confusableWith": [
      "Grasfrosch"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-erdkroete",
    "group": "animals",
    "number": 279,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Amphibia",
    "classGerman": "Amphibien",
    "order": "Anura",
    "orderGerman": "Froschlurche",
    "family": "Bufonidae",
    "familyGerman": "Kröten",
    "scientificName": "Bufo bufo",
    "displayName": "Bufo bufo",
    "genus": "Bufo",
    "germanName": "Erdkröte",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/erdkroete.jpg",
    "traits": [
      "warzig",
      "Kröten machen Laichschnüre",
      "überwintert im Boden"
    ],
    "confusableWith": [
      "Wechselkröte",
      "Grasfrosch"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-wechselkroete",
    "group": "animals",
    "number": 280,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Amphibia",
    "classGerman": "Amphibien",
    "order": "Anura",
    "orderGerman": "Froschlurche",
    "family": "Bufonidae",
    "familyGerman": "Kröten",
    "scientificName": "Bufotes viridis",
    "displayName": "Bufotes viridis",
    "genus": "Bufotes",
    "germanName": "Wechselkröte",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/wechselkroete.jpg",
    "traits": [
      "grüne Flecken",
      "glänzende goldene Augen",
      "Kröten machen Laichschnüre"
    ],
    "confusableWith": [
      "Erdkröte",
      "Gelbbauchunke"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-mauereidechse",
    "group": "animals",
    "number": 281,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Reptilia",
    "classGerman": "Reptilien",
    "order": "Squamata",
    "orderGerman": "Schuppenkriechtiere",
    "suborder": "Sauria",
    "suborderGerman": "Echsen",
    "family": "Lacertidae",
    "familyGerman": "Eidechsen",
    "scientificName": "Podarcis muralis",
    "displayName": "Podarcis muralis",
    "genus": "Podarcis",
    "germanName": "Mauereidechse",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/mauereidechse.jpg",
    "traits": [
      "Echse mit Beinen",
      "Lacertidae",
      "häutet sich als Ganzes laut Screenshotblock zu Squamata"
    ],
    "confusableWith": [
      "Zauneidechse"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-zauneidechse",
    "group": "animals",
    "number": 282,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Reptilia",
    "classGerman": "Reptilien",
    "order": "Squamata",
    "orderGerman": "Schuppenkriechtiere",
    "suborder": "Sauria",
    "suborderGerman": "Echsen",
    "family": "Lacertidae",
    "familyGerman": "Eidechsen",
    "scientificName": "Lacerta agilis",
    "displayName": "Lacerta agilis",
    "genus": "Lacerta",
    "germanName": "Zauneidechse",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/zauneidechse.jpg",
    "traits": [
      "kräftige Eidechse",
      "Männchen oft grünlich",
      "Lacertidae"
    ],
    "confusableWith": [
      "Mauereidechse"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-blindschleiche",
    "group": "animals",
    "number": 283,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Reptilia",
    "classGerman": "Reptilien",
    "order": "Squamata",
    "orderGerman": "Schuppenkriechtiere",
    "suborder": "Sauria",
    "suborderGerman": "Echsen",
    "family": "Anguidae",
    "familyGerman": "Schleichen",
    "scientificName": "Anguis fragilis",
    "displayName": "Anguis fragilis",
    "genus": "Anguis",
    "germanName": "Blindschleiche",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/blindschleiche.jpg",
    "traits": [
      "beinlose Echse",
      "keine Schlange",
      "glatte Oberfläche"
    ],
    "confusableWith": [
      "Ringelnatter",
      "Kreuzotter"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-ringelnatter",
    "group": "animals",
    "number": 284,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Reptilia",
    "classGerman": "Reptilien",
    "order": "Squamata",
    "orderGerman": "Schuppenkriechtiere",
    "suborder": "Serpentes",
    "suborderGerman": "Schlangen",
    "family": "Natricidae",
    "familyGerman": "Wassernattern",
    "scientificName": "Natrix natrix",
    "displayName": "Natrix natrix",
    "genus": "Natrix",
    "germanName": "Ringelnatter",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/ringelnatter.jpg",
    "traits": [
      "Natter",
      "runde Pupillen laut Screenshotblock zu Natricidae",
      "meist ohne Giftzähne"
    ],
    "confusableWith": [
      "Kreuzotter",
      "Blindschleiche"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-kreuzotter",
    "group": "animals",
    "number": 285,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Reptilia",
    "classGerman": "Reptilien",
    "order": "Squamata",
    "orderGerman": "Schuppenkriechtiere",
    "suborder": "Serpentes",
    "suborderGerman": "Schlangen",
    "family": "Viperidae",
    "familyGerman": "Ottern",
    "scientificName": "Vipera berus",
    "displayName": "Vipera berus",
    "genus": "Vipera",
    "germanName": "Kreuzotter",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/kreuzotter.jpg",
    "traits": [
      "Viper",
      "senkrechte Pupillen laut Screenshotblock zu Viperidae",
      "zwei Giftzähne im Oberkiefer"
    ],
    "confusableWith": [
      "Ringelnatter",
      "Blindschleiche"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-braunbrustigel",
    "group": "animals",
    "number": 286,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Mammalia",
    "classGerman": "Säugetiere",
    "order": "Eulipotyphla",
    "orderGerman": "Insektenfresser",
    "family": "Erinaceidae",
    "familyGerman": "Igel",
    "scientificName": "Erinaceus europaeus",
    "displayName": "Erinaceus europaeus",
    "genus": "Erinaceus",
    "germanName": "Braunbrustigel",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/braunbrustigel.jpg",
    "traits": [
      "Haare zu Stacheln umgebildet",
      "besondere Hautmuskulatur",
      "Winterschläfer"
    ],
    "confusableWith": [],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-wildkaninchen",
    "group": "animals",
    "number": 287,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Mammalia",
    "classGerman": "Säugetiere",
    "order": "Lagomorpha",
    "orderGerman": "Hasenartige",
    "family": "Leporidae",
    "familyGerman": "Hasen",
    "scientificName": "Oryctolagus cuniculus",
    "displayName": "Oryctolagus cuniculus",
    "genus": "Oryctolagus",
    "germanName": "Wildkaninchen",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/wildkaninchen.jpg",
    "traits": [
      "enge Choanen",
      "gesellig",
      "bauen Höhlen"
    ],
    "confusableWith": [
      "Nagetiere"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-europaeischer-biber",
    "group": "animals",
    "number": 288,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Mammalia",
    "classGerman": "Säugetiere",
    "order": "Rodentia",
    "orderGerman": "Nagetiere",
    "family": "Castoridae",
    "familyGerman": "Biberartige",
    "scientificName": "Castor fiber",
    "displayName": "Castor fiber",
    "genus": "Castor",
    "germanName": "Europäischer Biber",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/europaeischer-biber.jpg",
    "traits": [
      "staut Flüsse durch Fällen von Bäumen",
      "großer Nager",
      "flacher Schwanz"
    ],
    "confusableWith": [],
    "animalRequired": false,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": true
  },
  {
    "id": "animal-hausratte",
    "group": "animals",
    "number": 289,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Mammalia",
    "classGerman": "Säugetiere",
    "order": "Rodentia",
    "orderGerman": "Nagetiere",
    "family": "Muridae",
    "familyGerman": "Echte Mäuse",
    "scientificName": "Rattus rattus",
    "displayName": "Rattus rattus",
    "genus": "Rattus",
    "germanName": "Hausratte",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/hausratte.jpg",
    "traits": [
      "langer Schwanz",
      "große Ohren",
      "gefährdet laut Screenshotnotiz"
    ],
    "confusableWith": [
      "Wanderratte"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-wildkatze",
    "group": "animals",
    "number": 290,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Mammalia",
    "classGerman": "Säugetiere",
    "order": "Carnivora",
    "orderGerman": "Raubtiere",
    "family": "Felidae",
    "familyGerman": "Katzen",
    "scientificName": "Felis silvestris",
    "displayName": "Felis silvestris",
    "genus": "Felis",
    "germanName": "Wildkatze",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/wildkatze.jpg",
    "traits": [
      "Felidae",
      "Carnivora",
      "buschiger Schwanz mit Ringen möglich"
    ],
    "confusableWith": [
      "Hauskatze",
      "Rotfuchs"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-rotfuchs",
    "group": "animals",
    "number": 291,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Mammalia",
    "classGerman": "Säugetiere",
    "order": "Carnivora",
    "orderGerman": "Raubtiere",
    "family": "Canidae",
    "familyGerman": "Hunde",
    "scientificName": "Vulpes vulpes",
    "displayName": "Vulpes vulpes",
    "genus": "Vulpes",
    "germanName": "Rotfuchs",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/rotfuchs.jpg",
    "traits": [
      "Canidae",
      "rötliches Fell",
      "buschiger Schwanz"
    ],
    "confusableWith": [
      "Wildkatze"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-waldiltis",
    "group": "animals",
    "number": 292,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Mammalia",
    "classGerman": "Säugetiere",
    "order": "Carnivora",
    "orderGerman": "Raubtiere",
    "family": "Mustelidae",
    "familyGerman": "Marder",
    "scientificName": "Mustela putorius",
    "displayName": "Mustela putorius",
    "genus": "Mustela",
    "germanName": "Waldiltis",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/waldiltis.jpg",
    "traits": [
      "Mustelidae",
      "langgestreckter Körper",
      "maskenartige helle Gesichtspartien möglich"
    ],
    "confusableWith": [
      "Marder",
      "Frettchen"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-wildschwein",
    "group": "animals",
    "number": 293,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Mammalia",
    "classGerman": "Säugetiere",
    "order": "Artiodactyla",
    "orderGerman": "Paarhufer",
    "family": "Suidae",
    "familyGerman": "Schweine",
    "scientificName": "Sus scrofa",
    "displayName": "Sus scrofa",
    "genus": "Sus",
    "germanName": "Wildschwein",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/wildschwein.jpg",
    "traits": [
      "nicht wiederkäuend",
      "obere Eckzähne nach außen gerichtet",
      "fünfstrahlige Extremität zu zwei Strahlen reduziert"
    ],
    "confusableWith": [],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-gaemse",
    "group": "animals",
    "number": 294,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Mammalia",
    "classGerman": "Säugetiere",
    "order": "Artiodactyla",
    "orderGerman": "Paarhufer",
    "family": "Bovidae",
    "familyGerman": "Rinderartige",
    "scientificName": "Rupicapra rupicapra",
    "displayName": "Rupicapra rupicapra",
    "genus": "Rupicapra",
    "germanName": "Gämse",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/gaemse.jpg",
    "traits": [
      "Bovidae",
      "Hörner",
      "Gesichtszeichnung auffällig"
    ],
    "confusableWith": [
      "Mufflon",
      "Reh"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-mufflon",
    "group": "animals",
    "number": 295,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Mammalia",
    "classGerman": "Säugetiere",
    "order": "Artiodactyla",
    "orderGerman": "Paarhufer",
    "family": "Bovidae",
    "familyGerman": "Rinderartige",
    "scientificName": "Ovis orientalis musimon",
    "displayName": "Ovis orientalis musimon",
    "genus": "Ovis",
    "germanName": "Mufflon",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/mufflon.jpg",
    "traits": [
      "Bovidae",
      "Widder mit stark gebogenen Hörnern",
      "lateinischen Namen mit Kursliste abgleichen"
    ],
    "confusableWith": [
      "Gämse",
      "Reh"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  },
  {
    "id": "animal-reh",
    "group": "animals",
    "number": 296,
    "courseDay": "Tetrapoda",
    "sourcePage": "Tetrapoda-Screenshots",
    "taxonGroup": "Chordata",
    "subtaxonGroup": "Vertebrata",
    "className": "Mammalia",
    "classGerman": "Säugetiere",
    "order": "Artiodactyla",
    "orderGerman": "Paarhufer",
    "family": "Cervidae",
    "familyGerman": "Hirsche",
    "scientificName": "Capreolus capreolus",
    "displayName": "Capreolus capreolus",
    "genus": "Capreolus",
    "germanName": "Reh",
    "imageStatus": "included-user-screenshot",
    "imagePath": "assets/animals/tetrapoda/reh.jpg",
    "traits": [
      "Cervidae",
      "Geweih aus Knochen",
      "Geweih wird jährlich abgeworfen"
    ],
    "confusableWith": [
      "Gämse",
      "Mufflon"
    ],
    "animalRequired": true,
    "requiredLevel": "Art",
    "requiredSource": "rot markiert / Tetrapoda-Screenshot",
    "requiredUncertain": false
  }
];
  const existing = new Set(DATA.animals.map(x => x.id));
  entries.forEach(entry => { if (!existing.has(entry.id)) DATA.animals.push(entry); });
})();
